[package]
name = "adk-model"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
adk-core = { path = "../adk-core" }
adk-telemetry = { path = "../adk-telemetry" }
async-trait.workspace = true
tokio.workspace = true
futures.workspace = true
async-stream.workspace = true
serde_json.workspace = true
gemini = { workspace = true }
anyhow.workspace = true
tracing.workspace = true
