[package]
name = "adk-agent"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
adk-core = { path = "../adk-core" }
adk-model = { path = "../adk-model" }
adk-tool = { path = "../adk-tool" }
adk-telemetry = { path = "../adk-telemetry" }
async-trait = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
async-stream = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
dotenv = "0.15"
