[package]
name = "adk-tool"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
adk-core = { path = "../adk-core" }
adk-telemetry = { path = "../adk-telemetry" }
async-trait.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
schemars = "0.8"
rmcp = { version = "0.9", features = ["client"] }
tracing.workspace = true
